### ISSUE TITLE
Missing BOM

### ISSUE THREAD

**Issue by marciogranzotto** [YIO-Remote/hardware#1]
It would be great to have a Bill of Materials for each device

**Comment by dakaix** [comment]
Agreed, a BOM is needed here. My inductor (L1) was chipped during assembly and I'd like to source a replacement, but the markings on it aren't much use!

**Comment by shawly** [comment]
> As soon as the rewards are sent out, I’ll upload the necessary files so you can all make one.

_Source: https://community.yio-remote.com/t/i-was-too-late-for-the-party/468/6_

Guess we just have to be patient, with the current pandemic going on it's just taking a bit longer than expected.
